name: Windows Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-python
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-cmake

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -G"Unix Makefiles" -Bbuild .
          cmake --build build -j

      - name: Prepare artifact
        run: |
          mkdir -p bin/data
          cp build/pd.x86_64.exe bin/
          cp /mingw64/bin/{SDL2.dll,zlib1.dll,libwinpthread-1.dll,libgcc_s_seh-1.dll} bin/
          touch bin/data/put_your_rom_here.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: perfect-dark-windows
          path: bin/
